spin_manifest_version = 2

[application]
name = "m4p"
version = "0.1.7"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "m4p"

[component.m4p]
source = "target/wasm32-wasip2/release/m4p.wasm"
allowed_outbound_hosts = ["https://github.com", "https://fonts.gstatic.com", "https://raw.githubusercontent.com", "https://maps4print.com", "https://*.paypal.com"]
files = ["*", "."]

[component.m4p.build]
command = "cargo build --release --target wasm32-wasip2"
watch = ["src/**/*.rs", "Cargo.toml"]